### ISSUE TITLE
Why we must need to know js or jquery when we are interest only in php? 

### ISSUE THREAD

**Issue by ta-riq** [arif98741/pms#3]
As you wrote on the description,  If we wanna sharpen our skill on php,  we can contribute but then you say that we must need knowledge about js

But why sir?

**Comment by arif98741** [comment]
You need to know that jquery is a client side language interacts with browser. But it also can interact with server by HTTP Request which is ajax. For becoming a good developer and cope with the developing world it is needed to learn JavaScript and Jquery must. I hope that, you have got your answer clearly.

**Comment by ta-riq** [comment]
Thanks 

> **i got it.**
